---
title: "Check matrix correlations"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

# Checking the number of character replaced in each matrix


```{r}
library(ape)
## Setting the path
PATH <- "../Data/Simulations/Matrices/"
```

The following function counts, _a posteriori_ the number of characters that where replaced in each matrix (by comparing them to the normal matrix)

```{r}
## Getting the proportion of replaced characters
get.proportion.replace <- function(matrix, path) {
    ## Getting one matrix in a comparable format
    get.one.matrix <- function(path, matrix, type) {
        return(unlist(apply(do.call(rbind,
                                    read.nexus.data(paste0(path, matrix, "_", type, ".nex"))
                            ), 2, list), recursive = FALSE))
    }

    ## Getting all the matrices
    norm <- get.one.matrix(path, matrix, "norm")
    maxi <- get.one.matrix(path, matrix, "maxi")
    mini <- get.one.matrix(path, matrix, "mini")
    rand <- get.one.matrix(path, matrix, "rand")


    ## Comparing all the matrices
    n <- length(norm)
    maxi <- length(which(!mapply(function(X, Y) all(X == Y), norm, maxi)))/n
    mini <- length(which(!mapply(function(X, Y) all(X == Y), norm, mini)))/n
    rand <- length(which(!mapply(function(X, Y) all(X == Y), norm, rand)))/n

    return(c("maxi" = maxi, "mini" = mini, "rand" = rand))
}
```

We can then apply it to the list of matrices

```{r}
## Creating the placeholder list for the results
replacements <- list(list(), list(), list())
## getting the values to loop through
taxa_val <- c(25, 75, 150)
character_val <- c(100, 350, 1000)
for(taxa in 1:3) {
    for(character in 1:3) {
        ## Get the taxa names
        names <- unique(gsub("_[a-z]*.nex", "",
          list.files(PATH, pattern = paste0(taxa_val[taxa], "t_", character_val[character], "c_"))))
        ## Get the proportions of replaced characters
        replacements[[taxa]][[character]] <- lapply(as.list(names), get.proportion.replace, PATH)
    }
}

## Combining the results
fun.maxi <- function(list) {
    return(unlist(lapply(list, function(X) return(X[[1]]))))
}
fun.mini <- function(list) {
    return(unlist(lapply(list, function(X) return(X[[2]]))))
}
fun.rand <- function(list) {
    return(unlist(lapply(list, function(X) return(X[[3]]))))
}
results_maxi <- lapply(replacements, lapply, fun.maxi)
results_mini <- lapply(replacements, lapply, fun.mini)
results_rand <- lapply(replacements, lapply, fun.rand)

## Naming the lists
c("25t", "75t", "100t") -> names(results_maxi) -> names(results_mini) -> names(results_rand)
c("100c", "350c", "1000c") -> names(results_maxi[[1]]) ->
                              names(results_maxi[[2]]) ->
                              names(results_maxi[[3]]) ->
                              names(results_mini[[1]]) ->
                              names(results_mini[[2]]) ->
                              names(results_mini[[3]]) ->
                              names(results_rand[[1]]) ->
                              names(results_rand[[2]]) ->
                              names(results_rand[[3]])
```

We can then represent the results using box plots:

```{r, fig.height = 18, fig.width = 6}
## Plotting the different proportion results
plot.proportions <- function(data, ...) {
    ## Default colours
    cols <- gray.colors(3)
    ## Boxes
    boxplot(xlab = "", ylab = "Proportion of replacement", xaxt = "n", ylim = c(0, 1), col = cols,
            c(data[[1]], data[[2]], data[[3]]), ...)
    legend("topleft", legend = names(data), pch = 19, col = cols, bty = "n")
    ## X axis
    axis(1, 1:9, labels = FALSE, tick = FALSE)
    axis(1, c(2, 5, 8), tick = FALSE, labels = names(data))
    ## Lines
    abline(v = 3.5) ; abline(v = 6.5)
}

par(mfrow = c(3,1))
plot.proportions(results_maxi, main = "Maximised differences")
plot.proportions(results_mini, main = "Minimised differences")
plot.proportions(results_rand, main = "Randomised differences")

```


