---
title: "Effect of character correlation"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

# Effect of character correlation

## Loading the functions and the data

Getting the functions and the data.

```{r, eval = TRUE, message = FALSE}
library(dispRity)
library(lme4)
library(lmerTest)
source("functions.R") ; load.functions(test = FALSE)
load("../Data/NTS/matrix.nts.Rda")
source("../Data/load.data.R")

## Getting the whole data
whole_data <- list("t25" = t25_list, "t75" = t75_list, "t150" = t150_list)
```

```{r, echo = FALSE}
library(knitr)
library(xtable)
```

## Linear models

### Running a single linear model

Here we measure the eventual correlation between a low/high character correlation and a low/high RF or Triplets score.

```{r}
## Loading the matrices CD
matrices_cd <- get.matrix.CD(path = "../Data/Simulations/Matrices", "25t_100c", verbose = TRUE, length.out = 35)

## Running the model
model_out <- run.lm(matrices_cd, whole_data, chain = "25t_100c", method = "Bayesian", metric = "RF")

## Plotting the output

## Colour differences
col <- c("blue", "orange", "green")
rounding <- 3


```
