---
title: "Characters Correlation"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 8
    fig_height: 8
---

Characters Correlation
===============

What is the effect of morphological characters correlation on phylogenetic inference?

<!-- Before starting
===============

Loading the package
-----------------------------------

```{r, eval = FALSE}
# The latest version of devtools
if(!require(devtools)) install.packages("devtools")

## The latest version of dispRity 
install_github("TGuillerme/dispRity")
```

Loading the data
-----------------------------------

We're just going to use the iris data set here.


```{r}
set.seed(123)

## Loading the data
data(iris)
head(iris, 3)

## Isolating the variables
iris_variables <- iris[, 1:4]
iris_species <- iris[, 5]
```

Ordination
===============

Simple (classic ordination).

```{r}
## Simple basic ordination
iris_ord_simple <- prcomp(iris_variables)

## Relative variance explained by axis
iris_ord_simple_var <- iris_ord_simple[[1]]/sum(iris_ord_simple[[1]])

```

Plotting the ordination axis variance and the ordination

```{r, fig.width=8, fig.height=4}
## Graphical parameters 
op <- par(mfrow = c(1,2), bty = "n")

## Plotting the axis explained variance
barplot(iris_ord_simple_var, main = "explained variance")

## Plotting the ordination (axis 1 and 2)
plot(iris_ord_simple$x[,1], iris_ord_simple$x[,2], main = "2D ordination plot",
     xlab = paste("PC1 (", round(iris_ord_simple_var[1], digit = 2), ")", sep = ""),
     ylab = paste("PC2 (", round(iris_ord_simple_var[2], digit = 2), ")", sep = ""),
     pch = 19, col = palette()[as.factor(iris_species)])

## Adding the eigen vectors
for (rotation in 1:nrow(iris_ord_simple$rotation)) {
    # Isolating the coordinates
    coord_x <- iris_ord_simple$rotation[rotation,1]
    coord_y <- iris_ord_simple$rotation[rotation,2]
    # Eigen vectors
    lines(c(0, coord_x), c(0, coord_y), col = palette()[4])
    # Contributors
    text(x = coord_x*1.1, y = coord_y*1.1,
         rownames(iris_ord_simple$rotation)[rotation], cex =0.8)
}
par(op)
```

Note that here, Length and Width are kind of collinear and Sepal/Petal are orthogonal.


"Jack-knifing the ordination"
===============

Removing one variable each time for performing the ordination

```{r}
## Create a list of matrices minus one variable
matrix_list <- list(iris_variables[,-1],
                    iris_variables[,-2],
                    iris_variables[,-3],
                    iris_variables[,-4])
names(matrix_list) <- c("No_Sep.Len", "No_Sep.Wid", "No_Pet.Len", "No_Pet.Wid")

## Simple basic ordination
iris_ord_JN <- lapply(matrix_list, prcomp)

## Relative variance explained by axis
iris_ord_JN_var <- lapply(iris_ord_JN, function(X) X[[1]]/sum(X[[1]]))

```

Plotting the ordination axis variances

```{r, fig.width=8, fig.height=8}
## Graphical parameters 
op <- par(mfrow = c(2,2), bty = "n")
## Plotting the axis explained variance
for(JN in 1:length(matrix_list)) {
    barplot(iris_ord_JN_var[[JN]], main = paste("Var.", names(iris_ord_JN_var)[JN]))
}
par(op)
```

```{r, fig.width=8, fig.height=8}
## Graphical parameters 
op <- par(mfrow = c(2,2), bty = "n")

for(JN in 1:length(matrix_list)) {
    ## Plotting the ordination (axis 1 and 2)
    plot(iris_ord_JN[[JN]]$x[,1], iris_ord_JN[[JN]]$x[,2], main = names(iris_ord_JN)[JN],
         xlab = paste("PC1 (", round(iris_ord_JN[[JN]][[1]][1]/sum(iris_ord_JN[[JN]][[1]]),
         digit = 2), ")", sep = ""), ylab = paste("PC2 (",
         round(iris_ord_JN[[JN]][[1]][2]/sum(iris_ord_JN[[JN]][[1]]), digit = 2), ")", sep = ""),
         pch = 19, col = palette()[as.factor(iris_species)])

    ## Adding the eigen vectors
    for (rotation in 1:nrow(iris_ord_JN[[JN]]$rotation)) {
        # Isolating the coordinates
        coord_x <- iris_ord_JN[[JN]]$rotation[rotation,1]
        coord_y <- iris_ord_JN[[JN]]$rotation[rotation,2]
        # Eigen vectors
        lines(c(0, coord_x), c(0, coord_y), col = palette()[4])
        # Contributors
        text(x = coord_x*1.1, y = coord_y*1.1,
             rownames(iris_ord_JN[[JN]]$rotation)[rotation], cex =0.8)
    }
}
par(op)
```

And note here that collinearity and orthogonality is not quiet as much conserved!


A more complex example (from Anderson et al 2011 Nature)
===============

Loading the data
-----------------------------------

```{r}
## Loading the data
anderson_data <- read.csv("Anderson.et.al2011-Nature.csv", header = TRUE)
## Selecting the data subset
and_subdata <- anderson_data[,c(1,2,6:16)]
## Removing NAs (for the example here, shouldn't be a problem normaly)
data_clean <- and_subdata[-which(apply(apply(and_subdata, 1, is.na), 2, any) == TRUE), ]
## And now it looks something like that
head(data_clean[,1:5])
## Make the data a matrix with taxa as rownames (scaled matrix)
data_matrix <- scale(as.matrix(data_clean[-c(1:2)]))
rownames(data_matrix) <- data_clean[,2]
## Separating the phylogenetic groups
data_familly <- as.character(data_clean[,1])
## Fixing typo
data_familly[which(data_familly == "Placoderma")] <- "Placodermi"
```

Ordination
-----------------------------------

Simple ordination.

```{r}
## Simple basic ordination
ord_anderson <- prcomp(data_matrix)
## Relative variance explained by axis
ord_anderson_var <- ord_anderson[[1]]/sum(ord_anderson[[1]])
```

Plotting the ordination axis variance and the ordination.

```{r, fig.width=8, fig.height=4}
## Graphical parameters 
op <- par(mfrow = c(1,2), bty = "n")

## Plotting the axis explained variance
barplot(ord_anderson_var, main = "explained variance")

## Plotting the ordination (axis 1 and 2)
plot(ord_anderson$x[,1], ord_anderson$x[,2], main = "2D ordination plot",
     xlab = paste("PC1 (", round(ord_anderson_var[1], digit = 2), ")", sep = ""),
     ylab = paste("PC2 (", round(ord_anderson_var[2], digit = 2), ")", sep = ""),
     pch = 19, col = palette()[as.factor(data_familly)])

## Adding the eigen vectors
for (rotation in 1:nrow(ord_anderson$rotation)) {
    arrows_scaling = 5
    # Isolating the coordinates
    coord_x <- ord_anderson$rotation[rotation,1]*arrows_scaling
    coord_y <- ord_anderson$rotation[rotation,2]*arrows_scaling
    # Eigen vectors
    lines(c(0, coord_x), c(0, coord_y), col = palette()[length(levels(as.factor(data_familly)))+1])
    # Contributors
    text(x = coord_x*1.1, y = coord_y*1.1,
         rownames(ord_anderson$rotation)[rotation], cex =0.8)
}
par(op)
```

The variables are length and ratios of the jaw ([details here](http://www.nature.com/nature/journal/v476/n7359/extref/nature10207-s1.pdf)).


"Jack-knifing the ordination"
===============

Removing one variable each time for performing the ordination

```{r}
## Create a list of matrices minus one variable
matrix_list <- list(data_matrix[,-1],
                    data_matrix[,-2],
                    data_matrix[,-3],
                    data_matrix[,-4],
                    data_matrix[,-5],
                    data_matrix[,-6],
                    data_matrix[,-7],
                    data_matrix[,-8],
                    data_matrix[,-9],
                    data_matrix[,-10],
                    data_matrix[,-11])
names(matrix_list) <- c("-C1", "-C2", "-C3", "-C4", "-C5", "-C6", "-C7", "-C8", "-C9", "-C10",
    "-C11")

## Simple basic ordination
ord_anderson_JN <- lapply(matrix_list, prcomp)

## Relative variance explained by axis
ord_anderson_JN_var <- lapply(ord_anderson_JN, function(X) X[[1]]/sum(X[[1]]))
```

Plotting the ordination axis variances

```{r, fig.width=8, fig.height=8}
## Plot part 1
## Graphical parameters 
op <- par(mfrow = c(2,2), bty = "n")
## Plotting the axis explained variance
for(JN in 1:4) {
    barplot(ord_anderson_JN_var[[JN]], main = paste("Var.", names(ord_anderson_JN_var)[JN]))
}
par(op)
```
```{r, fig.width=8, fig.height=8}
## Plot part 2
## Graphical parameters 
op <- par(mfrow = c(2,2), bty = "n")
## Plotting the axis explained variance
for(JN in 5:8) {
    barplot(ord_anderson_JN_var[[JN]], main = paste("Var.", names(ord_anderson_JN_var)[JN]))
}
par(op)
```
```{r, fig.width=8, fig.height=8}
## Plot part 3
## Graphical parameters 
op <- par(mfrow = c(2,2), bty = "n")
## Plotting the axis explained variance
for(JN in 9:11) {
    barplot(ord_anderson_JN_var[[JN]], main = paste("Var.", names(ord_anderson_JN_var)[JN]))
}
par(op)
```

```{r, fig.width=8, fig.height=8}
## Plot part 1
## Graphical parameters 
op <- par(mfrow = c(2,2), bty = "n")

for(JN in 1:4) {
    ## Plotting the ordination (axis 1 and 2)
    plot(ord_anderson_JN[[JN]]$x[,1], ord_anderson_JN[[JN]]$x[,2],
         main = names(ord_anderson_JN)[JN], xlab = paste("PC1 (",
         round(ord_anderson_JN[[JN]][[1]][1]/sum(ord_anderson_JN[[JN]][[1]]), digit = 2), ")",
         sep = ""), ylab = paste("PC2 (",
         round(ord_anderson_JN[[JN]][[1]][2]/sum(ord_anderson_JN[[JN]][[1]]), digit = 2), ")",
         sep = ""), pch = 19, col = palette()[as.factor(data_familly)])

    ## Adding the eigen vectors
    for (rotation in 1:nrow(ord_anderson_JN[[JN]]$rotation)) {
        arrows_scaling = 5
        # Isolating the coordinates
        coord_x <- ord_anderson_JN[[JN]]$rotation[rotation,1]*arrows_scaling
        coord_y <- ord_anderson_JN[[JN]]$rotation[rotation,2]*arrows_scaling
        # Eigen vectors
        lines(c(0, coord_x), c(0, coord_y),
            col = palette()[length(levels(as.factor(data_familly)))+1])
        # Contributors
        text(x = coord_x*1.1, y = coord_y*1.1,
             rownames(ord_anderson_JN[[JN]]$rotation)[rotation], cex =0.8)
    }
}
par(op)
```

```{r, fig.width=8, fig.height=8}
## Plot part 2
## Graphical parameters 
op <- par(mfrow = c(2,2), bty = "n")

for(JN in 5:8) {
    ## Plotting the ordination (axis 1 and 2)
    plot(ord_anderson_JN[[JN]]$x[,1], ord_anderson_JN[[JN]]$x[,2],
         main = names(ord_anderson_JN)[JN], xlab = paste("PC1 (",
         round(ord_anderson_JN[[JN]][[1]][1]/sum(ord_anderson_JN[[JN]][[1]]), digit = 2), ")",
         sep = ""), ylab = paste("PC2 (",
         round(ord_anderson_JN[[JN]][[1]][2]/sum(ord_anderson_JN[[JN]][[1]]), digit = 2), ")",
         sep = ""), pch = 19, col = palette()[as.factor(data_familly)])

    ## Adding the eigen vectors
    for (rotation in 1:nrow(ord_anderson_JN[[JN]]$rotation)) {
        arrows_scaling = 5
        # Isolating the coordinates
        coord_x <- ord_anderson_JN[[JN]]$rotation[rotation,1]*arrows_scaling
        coord_y <- ord_anderson_JN[[JN]]$rotation[rotation,2]*arrows_scaling
        # Eigen vectors
        lines(c(0, coord_x), c(0, coord_y),
            col = palette()[length(levels(as.factor(data_familly)))+1])
        # Contributors
        text(x = coord_x*1.1, y = coord_y*1.1,
             rownames(ord_anderson_JN[[JN]]$rotation)[rotation], cex =0.8)
    }
}
par(op)
```

```{r, fig.width=8, fig.height=8}
## Plot part 3
## Graphical parameters 
op <- par(mfrow = c(2,2), bty = "n")

for(JN in 9:11) {
    ## Plotting the ordination (axis 1 and 2)
    plot(ord_anderson_JN[[JN]]$x[,1], ord_anderson_JN[[JN]]$x[,2],
         main = names(ord_anderson_JN)[JN], xlab = paste("PC1 (",
         round(ord_anderson_JN[[JN]][[1]][1]/sum(ord_anderson_JN[[JN]][[1]]), digit = 2), ")",
         sep = ""), ylab = paste("PC2 (",
         round(ord_anderson_JN[[JN]][[1]][2]/sum(ord_anderson_JN[[JN]][[1]]), digit = 2), ")",
         sep = ""), pch = 19, col = palette()[as.factor(data_familly)])

    ## Adding the eigen vectors
    for (rotation in 1:nrow(ord_anderson_JN[[JN]]$rotation)) {
        arrows_scaling = 5
        # Isolating the coordinates
        coord_x <- ord_anderson_JN[[JN]]$rotation[rotation,1]*arrows_scaling
        coord_y <- ord_anderson_JN[[JN]]$rotation[rotation,2]*arrows_scaling
        # Eigen vectors
        lines(c(0, coord_x), c(0, coord_y),
            col = palette()[length(levels(as.factor(data_familly)))+1])
        # Contributors
        text(x = coord_x*1.1, y = coord_y*1.1,
             rownames(ord_anderson_JN[[JN]]$rotation)[rotation], cex =0.8)
    }
}
par(op)
```
-->