---
title: "Modifying character differences"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 12
---

Before starting
===============

Loading the package
-----------------------------------

```{r, eval = FALSE}
## The latest version of devtools
if(!require(devtools)) install.packages("devtools")

## The latest version of dispRity 
install_github("TGuillerme/dispRity")

## The latest version of Claddis
install_github("graemetlloyd/Claddis")
```

Loading the functions
-----------------------------------


```{r}
library(Claddis) ; library(dispRity)
source("functions.R") ; load.functions(test = FALSE)

## Load the C libraries
dyn.load("../Functions/char.diff.so")

## Function for helping loading the matrices
find.non.numerics <- function(x) {
    options(warn = -1)
    if(is.na(as.numeric(x))) {
        return(TRUE)
    } else {
        return(FALSE)
    }
}

## Functions for helping the density plots
get.max.x <- function(density) return(max(density$x))
get.max.y <- function(density) return(max(density$y))
get.min.x <- function(density) return(min(density$x))
get.min.y <- function(density) return(min(density$y))
```
And loading one matrix from TreeBase.

```{r}
## Set up the matrices path
matrix_path = "../Data/100_Matrices"
files <- list.files(path = matrix_path, pattern = ".nex")

## Read one matrix
matrix <- ReadMorphNexus(paste(matrix_path, files[39], sep ="/"))$matrix
matrix[apply(matrix, c(1,2), find.non.numerics)] <- "?"

```

Modifying character differences in a matrix
===============

Maximising and minimising the differences
-----------------------------------

The maximisation or minimisation of the character differences works in a fairly straightforward way:

1. the quantiles for each character compared to all other characters is calculated (e.g. first character against all the other)
2. characters that have their last/first quantile lower/higher than the threshold (0.25 and 0.75) are then selected
3. the selected characters are randomly replaced by the characters left in the matrix

```{r}
## Maximising the character differences
matrix_max <- modify.matrix(matrix, "maximise", threshold = 0.25)
## Minimising the character differences
matrix_min <- modify.matrix(matrix, "minimise", threshold = 0.75)
```

Plotting the differences
-----------------------------------

Let's first plot the normal density profile of the matrix' character differences:

```{r, fig.width=6, fig.height=18, fig.align = 'center'}
## Graphical parameters
op <- par(mfrow = c(3,1), bty = "n")

## Plotting the density profile un-modified
plot.char.diff.density(matrix, main = "Original differences")

## Plotting the maximised matrix' density
plot.char.diff.density(matrix_max, main = "Maximised differences")

## Plotting the minimised matrix' density
plot.char.diff.density(matrix_min, main = "Minimised differences")
```
